### PR TITLE
Add new api calls

### PR DESCRIPTION
**Pull request by mattecalcio**
- Addition of 3 new API calls (getMember, getBulkMembers, updateMember)
- Altering of arguments relating to modifying of a specific user or users. Specifically we now accept user_token in place of user_email for unsubMember, suppressMember and also use it for the updateMember call.
- Updated all relevant tests and examples.
- Bumped up version to 1.0.7

@kamelkev @mailermailer

### CODE REVIEW

**Comment by kamelkev** [comment]
Went over the pull request, few quick questions:
- In tests/UnsubMemberTest.php I noticed that you changed a assertion related to a non-existent address from a 305 (not found) to a 302 (bad). What's going on there? I have a feeling for the first issue there may be an issue in the underlying interface if you simply changed that code so the test would pass.
- I noticed you are including a default timezone, is there a particular reason we need that? Absolute timestamp values seem ok here?

Otherwise things look good here.

**Comment by mattecalcio** [comment]
To address your points:

- Technically the error being returned now is correct as the value I'm providing for the test is actually bad data (it isn't formatted correctly to be an email). I could write another test case that will cover both cases. I'm not really sure what changed internally, but that seems correct to me

- I don't think it is necessary to set the default timezone but I kept getting the warning below. I guess I could set the timezone to `UTC` and that should be ok.
```
Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
```

**Comment by kamelkev** [comment]
Ah ok. I think we should do both of your suggestions. Long term both are better decisions for maintainability.

**Comment by kamelkev** [comment]
Hey Matteo,

Did you see my last note? 

-K

**Comment by mattecalcio** [comment]
Updated @kamelkev

**Pull request merged**
